version: '3.7'

services:
  mysql:
    image: mysql:5.7
    container_name: golang_flash_cards_mysql
    platform: linux/amd64
    volumes:
      - ./.mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 3313:3306
    networks:
      - golang-flash-cards-mysql-network

networks:
  golang-flash-cards-mysql-network:
    driver: bridge
